### ISSUE TITLE
So mod blacklisting is a thing now as well?

### ISSUE THREAD

**Issue by FinnT730** [canitzp/Mod-Blocker#1]
We have had player blacklisting, and now you want to do mod blacklisting? What type of problem you want to fix with this?
Why not have a good enough license? That will force people NOT to use them in modpacks....

**Comment by canitzp** [comment]
This mod aims to improve server security by not allowing certain mods on them. A server still decides which mod should be blocked or not blocked. This was done to prevent hacking or cheating.
Please explain which problems you have with this idea

**Comment by FinnT730** [comment]
Well, the idea is good. But the client can always lie to the server. A good example for this would be this: When I have X mod and you are blocking X mod, the client can say to the server that it would be the Y mod that is not on the blacklist.

**Comment by canitzp** [comment]
Yes of course can the client lie, but this mod makes the whole thing a bit more secure, not fully.
